# Définition des services
services:
    # Service nginx serveur HTTP (alpine)
    nginx:
        image: nginx:1.26-alpine
        restart: unless-stopped
        depends_on:
            - php
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/html
            # Fichier de configuration pour le serveur Nginx.
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    # service PHP-FPM
    php:
        build: .
        # PHP s'arrêtera lors d'un arrêt manuel avec 'docker stop php'.
        restart: unless-stopped
        depends_on:
            - mysql
            - mongodb
        volumes: 
            - ./:/var/www/html
        env_file:
            - .env.docker
    # Service Mysql
    mysql:
        image: mysql:8.0
        ports:
            - "3307:3306"
        restart: always
        env_file:
            - .env.docker
        volumes:
            - mysql_data:/var/lib/mysql
            # vitegourmandDBTest pour un démarrage avec des données de test déjà intégrées dans l'application
            # ou vitegourmandDBClean pour un démarrage avec une base vide prête à l'emploi
            - ./database/vitegourmandDBTest.sql:/docker-entrypoint-initdb.d/init.sql
            # - ./database/vitegourmandDBClean.sql:/docker-entrypoint-initdb.d/init.sql
    # Service MongoDB
    mongodb:
        image: mongo:7.0
        restart: unless-stopped
        env_file:
            - .env.docker
        volumes:
            - mongo_data:/data/db

volumes:
    mysql_data:
    mongo_data: