# Fichier de configuration pour Nginx
server {
    listen 80;
    server_name localhost;

    client_max_body_size 10M;

    # /public est le chemin de sorti de Symfony
    root /var/www/html/public;
    index index.php;

    # 'location' définit des règles pour certaines URL
    # Dans le cas où Nginx ne trouve pas l'URL demandé par un visiteur, il renverra vers l'index.php de Symfony
    location / {
        try_files $uri /index.php$is_args$args;
    }

    # Paramètre lié à PHP :
    location ~ \.php$ {
        # Port de lecture pour PHP, c'est sur ce port que Nginx va renvoyer les fichiers .php
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    # Cette règle refuse l'accès aux fichiers qui finissent par un point
    location ~ /\. {
        deny all;
        access_log off;
        log_not_found off;
    }
}
